# nikobusconnect/const.py

# Connect
BAUD_RATE = 9600
COMMANDS_HANDSHAKE = [
    "++++",
    "ATH0",
    "ATZ",
    "$10110000B8CF9D",
    "#L0",
    "#E0",
    "#L0",
    "#E1"
]
EXPECTED_HANDSHAKE_RESPONSE = "$0511"
HANDSHAKE_TIMEOUT = 60

# Message parser
BUTTON_COMMAND_PREFIX = "#S"
IGNORE_ANSWER = "$00"
FEEDBACK_REFRESH_COMMAND = "#R"
FEEDBACK_MODULE_ANSWER = "$1F"
COMMAND_PROCESSED = "#A"
CONTROLLER_ADDRESS = "$05"
MANUAL_REFRESH_COMMANDS = ["$1F", "$0F"]
